# Be sure to restart your server after you modify this file.

# Register your app at https://soundcloud.com/you/apps and copy&paste Client ID and Secret here
client_id: 'a3a740f4fdecdd897dc3aa2f5fb1c34f'
client_secret: 'a09acfe7f6fb8ba60f23ceb2d2412b23'

# Your secret key for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
secret_token: 'querweg0'

# Replace these defaults with the right values for your competition
# These will only be applied the first time you run `rake db:setup`
competition:
  host: 'Panic Room'
  title: 'Dj Contest - Arena Gols'
  intro: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam volutpat leo vitae leo rutrum ullamcorper. Maecenas in orci nulla. Aenean gravida adipiscing arcu at sodales.'
  description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam volutpat leo vitae leo rutrum ullamcorper. Maecenas in orci nulla. Aenean gravida adipiscing arcu at sodales. Donec nisl lacus, gravida sit amet aliquam vitae, pulvinar at sapien. Nullam congue convallis libero, ut luctus erat posuere eu. Fusce sit amet ante nisi, ac viverra ligula. Etiam vel velit tellus. Phasellus pharetra, ligula fermentum interdum lobortis, lorem arcu pulvinar urna, vel blandit augue augue pulvinar elit. Duis nec justo ut mi sollicitudin eleifend sed sit amet leo. Quisque aliquet quam eget tortor tincidunt malesuada. Vivamus at neque ut sem molestie vulputate ac id diam. Fusce ut pulvinar leo. Curabitur sit amet dui ut nulla venenatis pretium ac vel dolor. Aliquam id imperdiet arcu. Vestibulum molestie venenatis tellus, sed lobortis nisi sodales ac.'
  prizes: '* Prize 1'
  about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam volutpat leo vitae leo rutrum ullamcorper. Maecenas in orci nulla. Aenean gravida adipiscing arcu at sodales.'
  #group: ''
  #rules: ''
  #download: ''
  start_date:
  end_date:
